osx_image: xcode10.1
language: objective-c

env:
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=9.0"
    - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=12.0"
script:
  - xcodebuild clean build -project SemanticVersioning.xcodeproj -scheme "SemanticVersioning" -destination "$DESTINATION" -enableCodeCoverage YES test
after_success:
  - bash <(curl -s https://codecov.io/bash) -cF "$DESTINATION"