osx_image: xcode9.2
language: objective-c

env:
  - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=8.1"
  - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=9.0"
  - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=10.0"
  - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=11.1"
script:
  - xcodebuild clean build -project SemanticVersioning.xcodeproj -scheme "SemanticVersioning" -destination "$DESTINATION" -enableCodeCoverage YES test
after_success:
  - bash <(curl -s https://codecov.io/bash) -cF "$DESTINATION" -t cee9d255-69c0-455d-83d4-eb28f696a299
